name: Run Browser Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          run: flutter doctor -v

      - name: Setup chrome driver
        uses: nanasess/setup-chromedriver@v2

      - name: Run chrome driver
        run: |
          chromedriver --url-base=/wd/hub --port=4444 &

      # REF: https://remarkablemark.org/blog/2020/12/12/headless-test-in-github-actions-workflow/
      - name: Run headless browser tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: flutter drive --driver=test_driver/integration_test.dart --target integration_test/app_test.dart -d chrome --release --browser-name=chrome
