name: Run Browser Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Checkout flutter/web_installers repository
        uses: actions/checkout@v4
        with:
          repository: flutter/web_installers

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Run web installers
        run: |
          cd web_installers/packages/web_drivers/
          dart pub get
          dart lib/web_driver_installer.dart &
          sleep 20

      - name: Run chrome driver
        run: |
          chromedriver/chromedriver --port=4444 &
          sleep 5

      - name: Run browser tests
        run: flutter drive --driver=test_driver/integration_test.dart -d web-server --release --browser-name=chrome
